name: Hugo Build and Deploy

on: push

env:
  BASE_URL: ${{ (github.ref == 'refs/heads/master' && 'gen3.org') || 'alpha.gen3.org' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.100.2'
        extended: true

    - name: Setup Asciidoctor
      run: sudo apt-get install -y asciidoctor # support asciidoc files

    - name: Update Config (replace {BASE_URL})
      run: sed -i "s|{BASE_URL}|${BASE_URL}|g" config.yaml

    - name: Build Site
      run: hugo

    - name: Install AWS CLI
      uses: chrislennon/action-aws-cli@1.1

    - name: Deploy to S3
      run: |
        aws s3 cp public s3://${{ env.BASE_URL }}/ --recursive --region ${{ vars.AWS_REGION }} --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
